apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-helm
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    external-repo: "true"

spec:
  destination:
    name: in-cluster
    namespace: vault
  project: default
  source:
    path: ''
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.31.0
    chart: vault
    helm:
      parameters:
        - name: global.openshift
          value: "true"
        - name: server.dev.enabled
          value: "true"
        - name: injector.image.repository
          value: registry.connect.redhat.com/hashicorp/vault-k8s
        - name: injector.image.tag
          value: "1.7.0-ubi"
        - name: server.image.repository
          value: registry.connect.redhat.com/hashicorp/vault
        - name: server.image.tag
          value: "1.20.4-ubi"  
  sources: []
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-init
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "3"

spec:
  destination:
    name: in-cluster
    namespace: vault
  project: default
  source:
    repoURL: https://github.com/cdoan1-online/bootstrap-hcpfleet-2
    path: clusters/global/operators/vault
    targetRevision: HEAD
  sources: []
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
